# Generated by Django 6.1 on 2026-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Joshua Shneider', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Composer · Saxophonist · Arranger', max_length=200)),
                ('contact_email', models.EmailField(default='contact@joshuashneider.com', max_length=254)),
                ('bandcamp_url', models.URLField(blank=True, default='https://joshuashneider.bandcamp.com', help_text='External Bandcamp profile link used in nav')),
                ('hero_text', models.TextField(blank=True, default="Welcome to the website of Composer Joshua Shneider. Please take a look and a listen and let us know what you think — we'd love to hear from you!")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('header_banner', models.ImageField(blank=True, help_text='Wide banner image displayed in the site header', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
