# Generated by Django 6.1 on 2026-08-16 21:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandcampEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('embed_code', models.TextField(help_text='Paste the full &lt;iframe&gt; embed code from Bandcamp → Share/Embed')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL key, e.g. "bio" → /bio/', unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('hero_image_caption', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('nav_order', models.PositiveSmallIntegerField(default=10, help_text='Lower = earlier in nav')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='The ID after watch?v= or in youtu.be/ URL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
