# Generated by Django 6.1 on 2026-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='bandcampembed',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube: paste the full video URL — leave blank if using Bandcamp embed code', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(default='', help_text='Paste the full YouTube URL, e.g. https://www.youtube.com/watch?v=…', max_length=200),
        ),
        migrations.AlterField(
            model_name='bandcampembed',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Bandcamp: paste the full &lt;iframe&gt; embed code from Share/Embed'),
        ),
    ]
