# Generated by Django 6.1 on 2026-08-16 21:24

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('events', 'Events'), ('press', 'Press')], default='news', max_length=20)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in list view. Leave blank to auto-generate.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated: jazz, orchestra, recording', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
