# Generated by Django 6.1 on 2026-08-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='Optional: paste a YouTube URL to embed a video in the post', max_length=200),
        ),
    ]
